### ISSUE TITLE
SamplerPalette layout

### ISSUE THREAD

**Issue by dszakallas** [dszakallas/mixxx-launchpad#6]
Be. wrote:
>After some testing I found that adding more samplers doesn't use significantly more memory until tracks are loaded to them, so I increased it up to 8 rows (64 samplers). You could potentially use an entire Launchpad for samples. Note that the numbering of the sampler decks is a bit counterintuitive to accommodate both controllers that have a single row of samplers (most all-in-one controllers) and controllers like the Launchpad that have a bunch of rows for samplers. The sampler deck numbers increase across each row, so if you have two rows showing, the sampler decks on the left are 1-4 and 9-12, not 1-8. To users this is irrelevant, but it matters for making a mapping.

>I suggest mapping sampler buttons as follows:
Press unloaded: load selected track in library to sampler
Press loaded: cue_gotoandplay
Shift + press, playing: stop
Shift + press, not playing: eject

I think the best way to support this would be to create a preset that supports multiple channels. This preset could be called SamplerPalette and could come only in small size. In case of a palette, the channel selector could operate on ranges. Channel1 would map sampler1-16. Channel2 would map 17-32 and so forth. 
The remaining problem is that what to do with channel5-8 selectors, that won't have corresponding ranges, and that selecting is a bit complicated because these are not default presets, so the user has to switch to it after selecting another one.

**Comment by dszakallas** [comment]
Hey @mfep, first of all, thanks for your comment. 

When I created this issue, 2.1.0 was still in the alpha stage, and I wasn't sure if the mentioned feature would get shipped at all. At the time the Deere UI was pretty useless because of its poor performance, so it wasn't worth experimenting with this.

So I guess, finally we have a user demand for this feature. TBH, I haven't looked at Mixxx for a while. So I am interested in your use case first. Why would you like to map channels 1-4? AFAIK even the 64 samplers mode use deck 1-4 as full blown decks. A playable setup would be to use two Launchpads, one handling the first 4 decks, the other the sample decks.

**Comment by dszakallas** [comment]
nvm, I interchanged channels for decks in the lingo. I see your point, and it is completely valid.

**Comment by mfep** [comment]
Thanks for the quick response!

> The current layout cycling requires way too many steps

In my opinion, being able to super quickly switch between different layouts during a performance is not a priority, and it's not a major issue, if one have to cycle through 2 other layouts to get to the sampler.

> The last would involve a whole bigger problem, but I guess we have to make justice to that "(soon) customizable" claim in the pitch eventually. Actually it is not that hard to implement.

Again, this may apply only to my personal use case, but I think the current system can do with a couple more hard-coded options without becoming overwhelming.

> If we only use a 8x8 deck as a SamplerPalette, this problem would be mitigated largely, as only one Grande preset is there, so it is less of a hassle to switch.

This is totally valid, and a Grande sample palette is needed, to get back the "original" launchpad functionality. However, I think the introduction of small sized palettes cannot be avoided. Being able to launch samples with any layout is quite important from a performer's perspective.

**Comment by mfep** [comment]
Sure, it would perfectly fulfill my needs. Does this mean that I can expect the implementation of this matter in the near future? :slightly_smiling_face:

**Comment by dszakallas** [comment]
Yes, this doesn't sound too complicated.

**Comment by dszakallas** [comment]
- [ ] Modify preset template to enable having multiple decks.
- [ ] Create the SamplerPalette short preset and add to existing presets
  - 4x4 grid of play buttons (might need a better control)
  - offset decks by 4

**Comment by dszakallas** [comment]
sampler support for land in #69

**Comment by dszakallas** [comment]
This is part of release [3.0.0](https://github.com/dszakallas/mixxx-launchpad/releases/tag/v3.0.0).
