### ISSUE TITLE
Does not work.

### ISSUE THREAD

**Issue by SilasVt** [dszakallas/mixxx-launchpad#73]
I tried with the most current release and the one before that. Tried using the Launchpad MK2 ones and the ones for the Mini.

`Syntax error at line 12, column 8 in file /home/silasv/.mixxx/controllers/Novation-Launchpad Mini MK3-scripts.js

Error:  
Expected `:'`

**Comment by dszakallas** [comment]
Hey @SilasVt, thanks for reporting this. Could you share what version of Mixxx are you using? Note that [v3.0.0 dropped support for Mixxx 2.3](https://szakallas.eu/2023/05/06/mixxx-launchpad-3-is-out/#dropping-support-for-mixxx-23-and-below) (the latest stable release of Mixxx), you have to use at least Mixxx 2.4 (currently in beta), which you can download from here: https://mixxx.org/download/#beta.
